### ISSUE TITLE
Implement the Ouroboros Praos protocol

### ISSUE THREAD

**Issue by javierdiaz72** [input-output-hk/high-assurance-legacy#197]
Our goal is to formalize the implementation of the [Ouroboros Praos protocol](https://eprint.iacr.org/2017/573.pdf).

**Comment by sethahrenbach** [comment]
What is the status here? I have some formal verification skills, albeit in Coq, not Isabelle.

**Comment by javierdiaz72** [comment]
> What is the status here? I have some formal verification skills, albeit in Coq, not Isabelle.

Finished, currently polishing the code and improving the documentation, a PR will be available soon.
